### ISSUE TITLE
downloading content of company disclosures 

### ISSUE THREAD

**Issue by jpdeleon** [enzoampil/psequant#5]
`get_company_disclosures()` currently returns a dataframe. It is useful to have another function that downloads and parses its contents, e.g. a particular press release, by supplying say the document's Circular Number. Then it would be easy to run sentiment analysis, etc.

The url format of company disclosures in pse is cryptic: 
e.g. [https://edge.pse.com.ph/openDiscViewer.do?edge_no=8571ce07732abd9643ca035510b6ec2b](url)

Posting a request to [https://edge.pse.com.ph/announcements/form.do](url) seems to return only tables, not links to the actual document.

What do you think?

**Comment by enzoampil** [comment]
You basically read my mind on the next steps for that function. It's still a huge todo that could allow us to integrate a lot of NLP into psequant. I'll prioritize this as the next feature to work on, but also feel free to help out with a PR if you find a solution before I post an update :)

**Comment by enzoampil** [comment]
@jpdeleon URL issue should be resolved now. ```get_company_disclosures()``` now returns a df with a ```url``` columns that points to the url of the required doc :) Now the only thing left is to integrate scraping logic per disclosure type! (as indicated above).

**Comment by jpdeleon** [comment]
I pulled the changes and it worked! Inddeed, simply adding an `url` column in the `df` is the way to go.

**Comment by RadEdje** [comment]
Greetings,

Just wanted to congratulate you on this amazing python PINOY PSE lbrary.

Now for   my question;

I imported the following:

`from fastquant import get_company_disclosures`


but got this error on google  colab:

`ImportError                               Traceback (most recent call last)

<ipython-input-27-32491801d0ee> in <module>()
----> 1 from fastquant import get_company_disclosures

ImportError: cannot import name 'get_company_disclosures'
`

I thought it  could be a problem  with the     Kernel so I  restarted,  re-installed  fastquant and re-ran all  the  python  scripts but  still  couldn't  import get_company_discolsures.....

Any suggestions would be highly appreciated. Thanks.

**Comment by jpdeleon** [comment]
Hi @RadEdje, thanks for checking fastquant. You have to first initialize the DiseclosuresPSE class before being able to use the get_company_disclosures method.  Please see the example in this notebook:

https://github.com/enzoampil/fastquant/blob/master/examples/disclosures.ipynb

**Comment by jpdeleon** [comment]
@RadEdje Did it work for you? Please give us some feedback for improvements or feature requests if there are any. Thanks!
